/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_werezak_diskSpace_DiskSpace */

#ifndef _Included_com_werezak_diskSpace_DiskSpace
#define _Included_com_werezak_diskSpace_DiskSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_werezak_diskSpace_DiskSpace
 * Method:    getDiskSpace
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_werezak_diskSpace_DiskSpace_getDiskSpace
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
